write:
  description: Call ebusd write command.
  fields:
    call:
      description: Circuit, property name and value to set
      example: '{"circuit": "700", "name": "Hc1MaxFlowTempDesired", "value": 21}'